version: '3.8'

services:
  php_todo:
    build: .
    ports:
      - 8200:80
    volumes:
      - php_app:/var/www/html
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    restart: always
    hostname: ${DB_HOST}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
     - db:/var/lib/mysql
volumes:
 - php_app:
   db:      
